package:
  name: marketsworld_martingale
  version: 1.0

source:
  git_url: https://github.com/metaperl/binary-martingale.git

build:
  number: 1

requirements:
  build:
    - python
    - numpy

  run:
    - python
    - setuptools
    - numpy
    - splinter
    - argh
    - clint

  script: python setup.py install


test:

about:
  home: https://github.com/metaperl/binary-martingale
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml